export enum OrderStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  SUCCESSFUL = "SUCCESSFUL",
  FAILED = "FAILED",
  SELF_CANCELED = "SELF_CANCELED",
  SYSTEM_CANCELED = "SYSTEM_CANCELED",
}

export enum DiscountType {
  PERCENTAGE = "PERCENTAGE",
  AMOUNT = "AMOUNT",
}
